// Generated by scripts/generate-routes.mjs — Linq write proxies (paid, agent-facing).
import "@/app/api/capability/check-imessage/route";
import "@/app/api/capability/check-rcs/route";
import "@/app/api/chats/[chatId]/voicememo/route";
import "@/app/api/chats/[chatId]/messages/route";
import "@/app/api/messages/route";
import "@/app/api/messages/[messageId]/route";
import "@/app/api/messages/[messageId]/update/route";
import "@/app/api/messages/[messageId]/reactions/route";
import "@/app/api/attachments/route";
import "@/app/api/attachments/[attachmentId]/route";
