// Generated by scripts/generate-routes.mjs — ops SIWX (line config, allowlisted wallet).
import "@/app/api/contact-card/route";
import "@/app/api/phone-numbers/[phoneNumberId]/route";
import "@/app/api/available-number/route";
import "@/app/api/webhook-subscriptions/route";
import "@/app/api/webhook-subscriptions/[subscriptionId]/route";
