// Generated by scripts/generate-routes.mjs — side-effect imports register all routes.
import "@/lib/routes.linq.registry";
import "@/lib/routes.stablelinq.registry";
import "@/lib/routes.stablelinq-ops.registry";
